version: '3.9'

services:
  api:
    image: ghcr.io/113134-zea-martin/appdocker:latest
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=AcademiaNovitDB;Username=postgres;Password=MySecretPassword123
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - webapi-net

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecretPassword123
      POSTGRES_DB: AcademiaNovitDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webapi-net

volumes:
  postgres_data:

networks:
  webapi-net:
    driver: overlay
