version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecretPassword123!
    ports:
      - "5432:5432"
    networks:
      - app
    restart: unless-stopped

  appdocker:
    container_name: appdocker
    depends_on:
      - postgres
    image: ghcr.io/113134-zea-martin/appdocker:latest
    ports:
      - "8080:5000"
    restart: unless-stopped
    networks:
      - app
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=AcademiaNovitDB;Username=postgres;Password=MySecretPassword123!

networks:
  app:
    driver: bridge
