name: GH-build-DEV

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build

      - name: Run unit tests
        run: dotnet test

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            git clone https://github.com/novitsoftware/pipelines
            cd pipelines && dotnet build && cd Aplicacion && dotnet publish -c Release -o ./publish

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.debugmail.io
          server_port: 25
          username: ${{ secrets.DEBUGMAIL_USERNAME }}
          password: ${{ secrets.DEBUGMAIL_PASSWORD }}
          subject: "Pipeline completado - ${{ github.repository }}"
          body: "El pipeline se ejecutó correctamente. Detalles: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          to: mzeacardenas@gmail.com
          from: Martin Zea
